PR
GALLEGOOOO/Javascript-callbacks pull request #1
Opened 2023-12-11 16:10 UTC by GALLEGOOOO

2023-12-18 18:18 UTC, Manel0712 requested changes

2023-12-18 18:28 UTC, Manel0712 requested changes

2023-12-18 18:28 UTC, Manel0712 commented on exercise_01/index.js
> +);
Use the format const = function to execute + console.log(const)

2023-12-18 18:29 UTC, Manel0712 requested changes

2023-12-18 18:29 UTC, Manel0712 commented on exercise_01/index.js
> +
Use the format const = function to execute + console.log(const)

2023-12-18 18:29 UTC, Manel0712 commented on exercise_01/index.js
> +
Use the format const = function to execute + console.log(const)

2023-12-18 18:29 UTC, Manel0712 commented on exercise_01/index.js
> +
Use the format const = function to execute + console.log(const)

2023-12-18 18:29 UTC, Manel0712 commented on exercise_01/index.js
> +
Use the format const = function to execute + console.log(const)

2023-12-18 18:39 UTC, Manel0712 approved these changes

2024-01-07 10:46 UTC, tictools approved these changes

2024-01-08 18:39 UTC, merged